spring:
  profiles: dev

server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 5

logging:
  level:
    root: DEBUG
