spring:
  application:
    name: my-app

# Configuration par défaut
server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
