spring:
  profiles: prod

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/proddb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: produser
    password: prodpassword
    hikari:
      maximum-pool-size: 20

logging:
  level:
    root: ERROR
